Displaying board history[wip]
cybergizer-hq/retrospective pull request #457
Opened 2021-09-03 16:04 UTC by gaev-art

…l  boards when deleted or continue

2021-09-09 16:29 UTC, staevs requested changes

2021-09-09 16:29 UTC, staevs commented on app/javascript/components/board/board.jsx
>    const renderBoardAvatar = (boardAvatar, title) => {
переместить в отдельный компонент

2021-09-09 16:29 UTC, staevs commented on app/javascript/components/board/group-icons/group-icons.jsx
> +export const GroupIcons = ({users, usersCount}) => {
в чем отличие `users.length` и `uses.count`?

2021-09-09 16:29 UTC, staevs commented on app/javascript/components/board/board.jsx
>    if (!numberСhanges) numberСhanges = 1;
странное условие

2021-09-09 16:29 UTC, staevs commented on app/javascript/components/board/menu-icon/menu-icon.jsx
> +  const continueHandler = async () => {
почему эти методы объявляются здесь, хотя содержат только те методы и данные, которые передаются сверху?

2021-09-09 16:29 UTC, staevs commented on app/javascript/components/boards-container.jsx
> +  const historyBoardElement = historyBoards.map((board) => (
ненужная константа, перемести сразу в рендер

2021-09-28 11:51 UTC, Sooonne approved these changes

2021-09-30 08:54 UTC, Sooonne approved these changes

2021-09-30 13:38 UTC, staevs approved these changes

2021-09-30 16:57 UTC, merged